# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0be9134f944ae02a582677c24cda1613dcf8832a677f53fa48645c42dd6f0da104a9e3aa62f91fdb94fecb6ab7aec88560f4065a0e07ebbf5a440e77eb649505

test:
  secret_key_base: d41b51a2acc22c5a5caf8672ef231c8e1f5204f2d633e48832199efaa9a264a075fe6535a2d11af91a929a0509e0e2ec854c690b04f60c7212940bb4a0e2dc03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
